name: ChessKit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    uses: chesskit-app/workflows/test-swift-package.yml@master
    runs-on: macos-latest
    secrets: inherit
